AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  SuggestExtensions: false

plugins:
  - rubocop-yard

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false
